# Generated by Django 5.0 on 2023-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='extra_json',
            field=models.TextField(default={}),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
